version: '3.1'

services:
  server:
    image: prim/lsx-server:1.0.0
    build:
      context: "."
    restart: always
    container_name: "lsx_server"
    ports:
      - "3200:3100"
    # devices:
    #   - "/dev/snd:/dev/snd"

